"""init

Revision ID: 954914f5cd8c
Revises: 8151ce967c5b
Create Date: 2025-02-20 11:52:20.565552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954914f5cd8c'
down_revision: Union[str, None] = '8151ce967c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'course_id')
    # ### end Alembic commands ###
